# T5 config
model_name: "google-t5/t5-base"
dataset_name: "achrafothman/aslg_pc12"

max_input_length: 256
max_target_length: 256

logging_steps: 10

learning_rate: 0.0001
num_epochs: 5
train_batch_size: 4
eval_batch_size:  4
seed: 42
patience: 3  # early stopping