model_name: "facebook/bart-base"
dataset_name: "achrafothman/aslg_pc12"


max_source_length: 256
max_target_length: 256


output_dir: "results_BART"
logging_dir: "logs_BART"

num_train_epochs: 5
do_train: True
do_eval: True
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
warmup_steps: 500
weight_decay: 0.1
label_smoothing_factor: 0.1
predict_with_generate: True
logging_steps: 50
save_strategy: "epoch"
save_total_limit: 3